# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('payload', models.CharField(max_length=512)),
                ('success', models.BooleanField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sms_logs',
            },
        ),
    ]
